import React from 'react';
import {InteractionProvider,Cue,at} from './Interaction';
import {MascotSprite} from './MascotSprite';
import {PrescriptionShoppingCard} from './PrescriptionShoppingCard';
import {Check,ArrowUpRight,Mail,Water,Walk,Sun} from './Icons';
import './prescription-shopping.css';
import './demo-app.css';

const typed=(text:string,frame:number,rate=1)=>text.slice(0,Math.floor(Math.max(0,frame)*rate));
type Props={sceneId:string;step:number;stepFrame:number};
const Field=({label,value,active=false}:{label:string;value:string;active?:boolean})=><label className="d-field"><span>{label}</span><div className={`d-input ${active?'d-active':''}`}>{value}<span className="d-caret"/></div></label>;
const Action=({children,secondary=false,active=false}:{children:React.ReactNode;secondary?:boolean;active?:boolean})=><button type="button" className={`d-action ${secondary?'d-secondary':''} ${active?'d-action-active':''}`}>{children}<ArrowUpRight size={25}/><Cue id={typeof children==='string'?children:'Open email app'}/></button>;
const Task=({children,checked=false,active=false}:{children:React.ReactNode;checked?:boolean;active?:boolean})=><div className={`d-task ${active?'d-task-active':''}`}><span className={`d-check ${checked?'d-checked':''}`}>{checked&&<Check size={22}/>}<Cue id={typeof children==='string'?(children.startsWith('I reviewed')?'Email consent':children):''}/></span><span>{children}</span></div>;
const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`d-card ${className}`}>{children}</section>;
const Typed=({text,frame}:{text:string;frame:number})=><>{text.slice(0,Math.floor(Math.max(0,frame)*1.35))}<span className="d-type-caret"/></>;

const Today=({water=3,completed=false}:{water?:number;completed?:boolean})=><div className="d-today"><div className="d-today-intro"><div><span className="d-eyebrow">A LITTLE CARE GOES A LONG WAY</span><h2>Good morning, Alex.</h2><p>Keep your health notes and daily check-ins together.</p></div><span className="d-status">{completed?'Check-in saved ✓':'Your little wins today'}</span></div><div className="d-metrics">{[{title:'HYDRATION',icon:<Water size={34}/>,value:String(water),unit:'/ 8 glasses',note:'A sip now is a little win.'},{title:'MOVEMENT',icon:<Walk size={34}/>,value:'0',unit:'/ 30 minutes',note:'One small step counts.'},{title:'YOUR ENERGY',icon:<Sun size={34}/>,value:completed?'Good':'Check in',unit:completed?'today':'',note:'You don’t have to be at 100%.'}].map((m,i)=><Card key={m.title}><div className="d-metric-top">{m.icon}<span>{m.title}</span>{i===0&&<b className={water===4?'d-water-added':''}>＋<Cue id="Water"/></b>}</div><div className="d-metric-value">{m.value}<small>{m.unit}</small></div>{i===0?<div className="d-water-bars">{Array.from({length:8},(_,j)=><i key={j} className={j<water?'filled':''}/>)}</div>:<div className="d-metric-track"><i style={{width:i===1?'0%':'75%'}}/></div>}<p>{m.note}</p></Card>)}</div></div>;

const Welcome=({step,stepFrame}:Props)=>{
 if(step===3)return <Today/>;
 if(step===2)return <div className="d-chat-welcome"><MascotSprite size={170}/><h2>Hello. I am Baymax.</h2><p>Your Medical Personal Agent. What’s on your mind?</p><div className="d-suggestions"><span>Help me prepare for my doctor visit ↗</span><span>I need a prescription refill ↗</span><span>Draft a brief to my doctor ↗</span></div><div className="d-composer">Tell Baymax what you need…<b>↑</b></div></div>;
 return <Card className="d-welcome"><div className="d-welcome-copy"><span className="d-eyebrow">MEET YOUR CARE COMPANION</span><h2>A little adorable.<br/>A lot of love.</h2><p>I’ll help you make room for your health, even when life gets busy.</p><Field label="What should I call you?" value={step===1?typed('Alex',stepFrame-3,.35):''} active={step===1}/><Action active={step===1&&stepFrame>25}>Let’s take care of you</Action></div><div className="d-welcome-mascot"><MascotSprite size={360} greeting/></div></Card>;
};
const Care=({step,stepFrame}:Props)=>{
 if(step===5)return <Today water={stepFrame>at('care',5,'Water')?4:3} completed/>;
 if(step===0)return <div className="d-conversation">{stepFrame>32&&<div className="d-user-message">Help me prepare for my doctor visit</div>}{stepFrame>42&&<div className="d-response"><MascotSprite size={140}/><div><h2>Let’s make a plan.</h2></div></div>}<div className="d-composer">{stepFrame<=32?<Typed text="Help me prepare for my doctor visit" frame={stepFrame}/>: 'What else is on your mind?'}<b>↑<Cue id="Send"/></b></div></div>;
 if(step===3)return <Card className="d-energy"><span className="d-eyebrow">YOUR DAILY CHECK-IN</span><h2>How’s your energy?</h2><p>There’s no wrong answer. Start where you are.</p><div className="d-energy-options">{['Low','Okay','Good','Great'].map((v,i)=><div key={v} className={v==='Good'&&stepFrame>20?'selected':''}><span>{['☁','◒','☀','✦'][i]}</span>{v}<Cue id={v}/></div>)}</div><Action active={stepFrame>40}>Save my check-in</Action></Card>;
 return <div className="d-two-column"><Card className="d-plan"><span className="d-eyebrow">YOUR PREPARATION PLAN</span><h2>Your next appointment.<br/>A little more prepared.</h2><div className="d-fields-row"><Field label="Appointment" value="Primary care visit"/><Field label="Date" value="October 10, 2026"/></div><Task checked={step>2||(step===2&&stepFrame>at('care',2,'Write down my symptoms'))} active={step===2}>Write down my symptoms</Task><Task checked={(step>2||(step===2&&stepFrame>at('care',2,'Review my medication list')))}>Review my medication list</Task><Task>Prepare questions for my doctor</Task><div className="plan-next"><Action active={step===2&&stepFrame>40}>Check in for today</Action></div></Card><div className="d-care-side"><MascotSprite size={230}/>{step===4?<><div className="d-success"><Check size={30}/> Check-in saved</div><h3>Good energy today.</h3><p>Thank you for making a little time for yourself.</p></>:<><h3>A small step counts.</h3><p>Check off a little win,<br/>then check in with yourself.</p><Action active={step===2&&stepFrame>40}>Check in for today</Action></>}</div></div>;
};
const Travel=({step,stepFrame}:Props)=>{
 if(step===3)return <Brief sceneId="brief" step={0} stepFrame={100}/>;
 return <div className="d-two-column d-travel"><Card><span className="d-eyebrow">YOUR TRAVEL DETAILS</span><h2>Let’s get you ready.</h2><Field label="Destination" value={step===0?typed('San Francisco, USA',stepFrame-4,.8):'San Francisco, USA'} active={step===0}/><Field label="Departure date" value="October 9, 2026"/><p className="d-notice">Confirm local requirements with your clinician or pharmacy.</p><Action active={step===0}>Prepare checklist</Action></Card>{step>=1?<Card><span className="d-eyebrow">MEDICATION TRAVEL CHECKLIST</span><h2>A few things to bring.</h2><Task checked={step>=2&&stepFrame>12}>Confirm remaining supply with your clinician</Task><Task checked={step>=2&&stepFrame>28}>Bring prescription and medication packaging</Task><Task>Ask a local pharmacist about refill requirements</Task><Task>Prepare a doctor brief</Task><Action active={step===2}>Open doctor brief</Action></Card>:<div className="d-travel-placeholder"><MascotSprite size={280}/><h3>Your care, packed and ready.</h3><p>A little preparation makes a new place<br/>feel less unfamiliar.</p></div>}</div>;
};
const briefText='Health brief for Alex\n\nReason for visit: Establishing care while travelling.\nCurrent medications: Review my existing prescription.\nAllergies: Confirm together at the appointment.\nQuestions: Which records should I bring?';
const Brief=({step,stepFrame}:Props)=>{
 if(step===3&&stepFrame>46)return <Card className="d-energy"><div style={{display:'flex',justifyContent:'center'}}><MascotSprite size={190}/></div><h2>Your draft is ready.</h2><p>Review and send from your email app.</p><div className="d-status">Prepared for doctor@example.org · Not sent</div></Card>;
 if(step>=2)return <Card className="d-email-review"><div className="d-review-header"><div><span className="d-eyebrow">REVIEW BEFORE SENDING</span><h2>Your doctor’s email.</h2></div><span className="d-status">Not sent yet</span></div><div className="d-email-columns"><div><p className="d-email-meta"><b>To:</b> doctor@example.org<br/><b>Subject:</b> My health brief for our appointment</p><pre className="d-brief-text">{briefText}</pre></div><div className="d-email-actions"><Task checked={step===3&&stepFrame>14} active={step===3}>I reviewed the recipient and approve including this brief in an email draft.</Task><Action active={step===3&&stepFrame>14}><Mail size={27}/> Open email app</Action><p>Your email app handles the final send.<br/>You choose when to share.</p></div></div></Card>;
 return <div className="d-two-column d-doctor"><Card><span className="d-eyebrow">REVIEW BEFORE YOU SHARE</span><h2>A brief for your next doctor.</h2><span className="d-field-label">Editable health brief</span><pre className={`d-brief-text ${step===0?'d-editing':''}`}>{briefText}</pre><Action secondary>Download a copy</Action></Card><Card><span className="d-eyebrow">YOU CHOOSE WHAT TO SHARE</span><h2>Email your doctor.</h2><Field label="Doctor’s email address" value={step>=1?typed('doctor@example.org',stepFrame-2,.9):''} active={step===1}/><Field label="Email subject" value="My health brief for our appointment"/><p className="d-notice">Verify medications, allergies and history before sharing.</p><Action active={step===1}>Review email</Action></Card></div>;
};
export const DemoApp:React.FC<Props>=props=>{
 const {sceneId,step,stepFrame}=props;
 return <InteractionProvider scene={sceneId} step={step} frame={stepFrame}><div className="component-app" data-demo-scene={sceneId} data-demo-step={step}><div className="d-app-header"><div className="d-agent"><MascotSprite size={72}/><div><b>Baymax</b><span>Here when you need me</span></div></div><div className="d-app-nav">{['Today','Talk to Baymax','Your plan','Travel care','Doctor brief'].map(n=><span key={n} className={((sceneId==='welcome'&&step===3)||(sceneId==='care'&&step===5)?'Today':sceneId==='welcome'||sceneId==='care'?'Talk to Baymax':sceneId==='travel'?'Travel care':sceneId==='brief'?'Doctor brief':'Talk to Baymax')===n?'active':''}>{n}<Cue id={n}/></span>)}</div></div><div className="d-app-content" >{sceneId==='welcome'?<Welcome {...props}/>:sceneId==='care'?<Care {...props}/>:sceneId==='travel'?<Travel {...props}/>:sceneId==='brief'?<Brief {...props}/>:<PrescriptionShoppingCard demoState={{productId:(step>1||(step===1&&stepFrame>14))?'glucose':'metformin',quantity:(step>1||(step===1&&stepFrame>37))?2:1,stage:step>=4?'complete':step>=2?'review':'cart',consent:step>3||(step===3&&stepFrame>10)}}/>}</div></div></InteractionProvider>;
};
