import React from 'react';
import {useCurrentFrame} from 'remotion';
import {Cue,InteractionProvider} from './Interaction';
import {MascotSprite} from './MascotSprite';
const goals=[{icon:'◷',title:'Stay on top of medications',detail:'Reminders and refill planning'},{icon:'♡',title:'Prepare for appointments',detail:'Your notes, questions, and records'},{icon:'◉',title:'Build a daily routine',detail:'Small goals and gentle check-ins'}];
export const OnboardingDemo=()=>{
 const f=useCurrentFrame();const step=Math.min(3,Math.floor(f/100));const local=f-step*100;
 const selected=(i:number)=>step>0?i<2:i===0?local>20:i===1&&local>45;
 return <InteractionProvider scene="onboarding" step={step} frame={local}><div className="onboarding-stage"><div className="onboarding-steps">{['Your goals','Medical records','Review'].map((label,i)=><span className={step>=i?'active':''} key={label}><b>{step>i?'✓':i+1}</b>{label}</span>)}</div>
 {step===0?<><h2>What would you like help with?</h2><p className="onboarding-subtitle">Choose what matters to you. You can change this anytime.</p><div className="goal-options">{goals.map((g,i)=><div key={g.title} className={`goal-option ${selected(i)?'selected':''}`}><span className="goal-icon">{g.icon}</span><div><h3>{g.title}</h3><p>{g.detail}</p></div><span className="goal-check">{selected(i)?'✓':''}</span><Cue id={g.title}/></div>)}</div><button className="onboarding-action">Set my goals <span>↗</span><Cue id="Set my goals"/></button></>:
 step===1?<><h2>Bring your medical history.</h2><p className="onboarding-subtitle">Add a PDF or a photo. Review the details before saving.</p><div className="record-dropzone"><div className="record-format"><span>PDF</span><span>IMG</span></div><h3>Prescriptions, visit notes, or lab reports</h3><p>PDF · JPG · PNG</p><button className="onboarding-action">Choose files <span>＋</span><Cue id="Choose files"/></button></div>{local>35&&<div className="record-files"><span>▤ &nbsp; Visit-summary.pdf <b>✓ Added</b></span><span>▧ &nbsp; Prescription.jpg <b>✓ Added</b></span></div>}<div className="onboarding-note">Only add records you want Baymax to use.</div></>:
 step===2?<><h2>Review your medical details.</h2><p className="onboarding-subtitle">Check the extracted information. Edit anything that needs correcting.</p><div className="record-review"><div><span>From Visit-summary.pdf</span><h3>Medical history</h3><p>Primary care visit summary</p></div><div><span>From Prescription.jpg</span><h3>Medication list</h3><p>Confirm names, strengths, and instructions</p></div><div><span>Needs your confirmation</span><h3>Allergies</h3><p>Add or confirm your allergies</p></div></div><div className="record-approval"><span>{local>35?'✓':'○'}</span>I’ve reviewed these details.<Cue id="Review details"/></div><button className="onboarding-action">Save and continue <span>↗</span><Cue id="Save and continue"/></button></>:
 <div className="onboarding-done"><MascotSprite size={190}/><h2>Your care starts here.</h2><p>Your goals and reviewed records are ready.</p><div className="onboarding-summary"><span>✓ Medication reminders</span><span>✓ Appointment preparation</span><span>✓ Medical records reviewed</span></div></div>}
 </div></InteractionProvider>;
};
